apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx1
  namespace: nginx1
spec:
  secretName: nginx1
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
  - 'nginx1.omriv.com'
